export interface CityRef {
  name: string
  region: string
  latitude: number
  longitude: number
  slug?: string
}

export const FEATURED: CityRef[] = [
  { slug: 'seattle', name: 'Seattle', region: 'Washington', latitude: 47.61, longitude: -122.33 },
  { slug: 'san-francisco', name: 'San Francisco', region: 'California', latitude: 37.77, longitude: -122.42 },
  { name: 'Los Angeles', region: 'California', latitude: 34.05, longitude: -118.24 },
  { name: 'San Diego', region: 'California', latitude: 32.72, longitude: -117.16 },
  { name: 'Portland', region: 'Oregon', latitude: 45.52, longitude: -122.68 },
  { name: 'New York', region: 'New York', latitude: 40.71, longitude: -74.01 },
  { name: 'Boston', region: 'Massachusetts', latitude: 42.36, longitude: -71.06 },
  { name: 'Washington', region: 'District of Columbia', latitude: 38.91, longitude: -77.04 },
  { name: 'Philadelphia', region: 'Pennsylvania', latitude: 39.95, longitude: -75.17 },
  { name: 'Chicago', region: 'Illinois', latitude: 41.88, longitude: -87.63 },
  { name: 'Minneapolis', region: 'Minnesota', latitude: 44.98, longitude: -93.27 },
  { name: 'Detroit', region: 'Michigan', latitude: 42.33, longitude: -83.05 },
  { name: 'Denver', region: 'Colorado', latitude: 39.74, longitude: -104.99 },
  { name: 'Phoenix', region: 'Arizona', latitude: 33.45, longitude: -112.07 },
  { name: 'Las Vegas', region: 'Nevada', latitude: 36.17, longitude: -115.14 },
  { name: 'Dallas', region: 'Texas', latitude: 32.78, longitude: -96.8 },
  { name: 'Houston', region: 'Texas', latitude: 29.76, longitude: -95.37 },
  { name: 'Austin', region: 'Texas', latitude: 30.27, longitude: -97.74 },
  { name: 'Atlanta', region: 'Georgia', latitude: 33.75, longitude: -84.39 },
  { name: 'Miami', region: 'Florida', latitude: 25.76, longitude: -80.19 },
  { name: 'New Orleans', region: 'Louisiana', latitude: 29.95, longitude: -90.07 },
  { name: 'Honolulu', region: 'Hawaii', latitude: 21.31, longitude: -157.86 },
  { name: 'Anchorage', region: 'Alaska', latitude: 61.22, longitude: -149.9 },
  { name: 'Toronto', region: 'Ontario, Canada', latitude: 43.65, longitude: -79.38 },
  { name: 'Vancouver', region: 'British Columbia, Canada', latitude: 49.28, longitude: -123.12 },
  { name: 'Montreal', region: 'Quebec, Canada', latitude: 45.5, longitude: -73.57 },
  { name: 'Calgary', region: 'Alberta, Canada', latitude: 51.05, longitude: -114.07 },
  { name: 'Mexico City', region: 'Mexico', latitude: 19.43, longitude: -99.13 },
  { name: 'Guadalajara', region: 'Jalisco, Mexico', latitude: 20.67, longitude: -103.35 },
  { name: 'Bogotá', region: 'Colombia', latitude: 4.71, longitude: -74.07 },
  { name: 'Lima', region: 'Peru', latitude: -12.05, longitude: -77.04 },
  { name: 'São Paulo', region: 'Brazil', latitude: -23.55, longitude: -46.63 },
  { name: 'Rio de Janeiro', region: 'Brazil', latitude: -22.91, longitude: -43.17 },
  { name: 'Buenos Aires', region: 'Argentina', latitude: -34.6, longitude: -58.38 },
  { name: 'Santiago', region: 'Chile', latitude: -33.45, longitude: -70.67 },
  { name: 'London', region: 'England, United Kingdom', latitude: 51.51, longitude: -0.13 },
  { name: 'Paris', region: 'France', latitude: 48.86, longitude: 2.35 },
  { name: 'Berlin', region: 'Germany', latitude: 52.52, longitude: 13.41 },
  { name: 'Madrid', region: 'Spain', latitude: 40.42, longitude: -3.7 },
  { name: 'Barcelona', region: 'Spain', latitude: 41.39, longitude: 2.16 },
  { name: 'Rome', region: 'Italy', latitude: 41.9, longitude: 12.5 },
  { name: 'Milan', region: 'Italy', latitude: 45.46, longitude: 9.19 },
  { name: 'Amsterdam', region: 'Netherlands', latitude: 52.37, longitude: 4.89 },
  { name: 'Brussels', region: 'Belgium', latitude: 50.85, longitude: 4.35 },
  { name: 'Zurich', region: 'Switzerland', latitude: 47.38, longitude: 8.54 },
  { name: 'Vienna', region: 'Austria', latitude: 48.21, longitude: 16.37 },
  { name: 'Prague', region: 'Czechia', latitude: 50.09, longitude: 14.42 },
  { name: 'Warsaw', region: 'Poland', latitude: 52.23, longitude: 21.01 },
  { name: 'Budapest', region: 'Hungary', latitude: 47.5, longitude: 19.04 },
  { name: 'Stockholm', region: 'Sweden', latitude: 59.33, longitude: 18.07 },
  { name: 'Oslo', region: 'Norway', latitude: 59.91, longitude: 10.75 },
  { name: 'Copenhagen', region: 'Denmark', latitude: 55.68, longitude: 12.57 },
  { name: 'Helsinki', region: 'Finland', latitude: 60.17, longitude: 24.94 },
  { name: 'Dublin', region: 'Ireland', latitude: 53.35, longitude: -6.26 },
  { name: 'Lisbon', region: 'Portugal', latitude: 38.72, longitude: -9.14 },
  { name: 'Athens', region: 'Greece', latitude: 37.98, longitude: 23.73 },
  { name: 'Moscow', region: 'Russia', latitude: 55.76, longitude: 37.62 },
  { name: 'Istanbul', region: 'Turkey', latitude: 41.01, longitude: 28.98 },
  { name: 'Kyiv', region: 'Ukraine', latitude: 50.45, longitude: 30.52 },
  { name: 'Cairo', region: 'Egypt', latitude: 30.04, longitude: 31.24 },
  { name: 'Lagos', region: 'Nigeria', latitude: 6.52, longitude: 3.38 },
  { name: 'Nairobi', region: 'Kenya', latitude: -1.29, longitude: 36.82 },
  { name: 'Johannesburg', region: 'South Africa', latitude: -26.2, longitude: 28.04 },
  { name: 'Cape Town', region: 'South Africa', latitude: -33.93, longitude: 18.42 },
  { name: 'Casablanca', region: 'Morocco', latitude: 33.57, longitude: -7.59 },
  { name: 'Addis Ababa', region: 'Ethiopia', latitude: 9.03, longitude: 38.74 },
  { name: 'Dubai', region: 'United Arab Emirates', latitude: 25.2, longitude: 55.27 },
  { name: 'Riyadh', region: 'Saudi Arabia', latitude: 24.71, longitude: 46.68 },
  { name: 'Tel Aviv', region: 'Israel', latitude: 32.09, longitude: 34.78 },
  { name: 'Tehran', region: 'Iran', latitude: 35.69, longitude: 51.39 },
  { name: 'Mumbai', region: 'India', latitude: 19.08, longitude: 72.88 },
  { name: 'Delhi', region: 'India', latitude: 28.61, longitude: 77.21 },
  { name: 'Bengaluru', region: 'India', latitude: 12.97, longitude: 77.59 },
  { name: 'Kolkata', region: 'India', latitude: 22.57, longitude: 88.36 },
  { name: 'Karachi', region: 'Pakistan', latitude: 24.86, longitude: 67.01 },
  { name: 'Dhaka', region: 'Bangladesh', latitude: 23.81, longitude: 90.41 },
  { name: 'Bangkok', region: 'Thailand', latitude: 13.76, longitude: 100.5 },
  { name: 'Singapore', region: 'Singapore', latitude: 1.35, longitude: 103.82 },
  { name: 'Jakarta', region: 'Indonesia', latitude: -6.21, longitude: 106.85 },
  { name: 'Manila', region: 'Philippines', latitude: 14.6, longitude: 120.98 },
  { name: 'Ho Chi Minh City', region: 'Vietnam', latitude: 10.82, longitude: 106.63 },
  { name: 'Kuala Lumpur', region: 'Malaysia', latitude: 3.14, longitude: 101.69 },
  { name: 'Hong Kong', region: 'Hong Kong', latitude: 22.32, longitude: 114.17 },
  { name: 'Taipei', region: 'Taiwan', latitude: 25.03, longitude: 121.57 },
  { name: 'Shanghai', region: 'China', latitude: 31.23, longitude: 121.47 },
  { name: 'Beijing', region: 'China', latitude: 39.9, longitude: 116.41 },
  { name: 'Guangzhou', region: 'China', latitude: 23.13, longitude: 113.26 },
  { name: 'Tokyo', region: 'Japan', latitude: 35.68, longitude: 139.69 },
  { name: 'Osaka', region: 'Japan', latitude: 34.69, longitude: 135.5 },
  { name: 'Seoul', region: 'South Korea', latitude: 37.57, longitude: 126.98 },
  { name: 'Sydney', region: 'New South Wales, Australia', latitude: -33.87, longitude: 151.21 },
  { name: 'Melbourne', region: 'Victoria, Australia', latitude: -37.81, longitude: 144.96 },
  { name: 'Brisbane', region: 'Queensland, Australia', latitude: -27.47, longitude: 153.03 },
  { name: 'Auckland', region: 'New Zealand', latitude: -36.85, longitude: 174.76 },
  { name: 'Wellington', region: 'New Zealand', latitude: -41.29, longitude: 174.78 },
]

export function sameCity(a: CityRef, b: CityRef): boolean {
  return Math.hypot(a.latitude - b.latitude, a.longitude - b.longitude) < 0.15
}

export function cityKey(city: CityRef): string {
  return `${city.latitude.toFixed(2)},${city.longitude.toFixed(2)}`
}
